/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author cristian
 */
public class Calculadora extends javax.swing.JFrame {

  /**
   * Creates new form Calculadora
   */
  public Calculadora() {
    initComponents();
    setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollBar1 = new javax.swing.JScrollBar();
    cabecera_pan = new javax.swing.JPanel();
    superior = new javax.swing.JLabel();
    campo = new javax.swing.JTextField();
    botones_pan = new javax.swing.JPanel();
    jPanel3 = new javax.swing.JPanel();
    clear_btn = new javax.swing.JButton();
    clearAll_btn = new javax.swing.JButton();
    vacio = new javax.swing.JLabel();
    vacio1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    boton7 = new javax.swing.JButton();
    boton8 = new javax.swing.JButton();
    boton9 = new javax.swing.JButton();
    botonDiv = new javax.swing.JButton();
    boton4 = new javax.swing.JButton();
    boton5 = new javax.swing.JButton();
    boton6 = new javax.swing.JButton();
    botonMul = new javax.swing.JButton();
    boton1 = new javax.swing.JButton();
    boton2 = new javax.swing.JButton();
    boton3 = new javax.swing.JButton();
    botonRes = new javax.swing.JButton();
    botonPunto = new javax.swing.JButton();
    boton0 = new javax.swing.JButton();
    botonResultado = new javax.swing.JButton();
    botonSum = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Calculadora");
    setPreferredSize(new java.awt.Dimension(250, 300));
    setResizable(false);

    cabecera_pan.setLayout(new java.awt.BorderLayout());

    superior.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
    superior.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    superior.setText(" ");
    superior.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
    cabecera_pan.add(superior, java.awt.BorderLayout.PAGE_START);

    campo.setEditable(false);
    campo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
    campo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
    campo.setText("0");
    campo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
    cabecera_pan.add(campo, java.awt.BorderLayout.PAGE_END);

    getContentPane().add(cabecera_pan, java.awt.BorderLayout.NORTH);

    botones_pan.setLayout(new java.awt.BorderLayout());

    jPanel3.setLayout(new java.awt.GridLayout(1, 0, 4, 4));

    clear_btn.setText("CE");
    clear_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clear_btnActionPerformed(evt);
      }
    });
    jPanel3.add(clear_btn);

    clearAll_btn.setText("C");
    clearAll_btn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        clearAll_btnActionPerformed(evt);
      }
    });
    jPanel3.add(clearAll_btn);
    jPanel3.add(vacio);
    jPanel3.add(vacio1);

    botones_pan.add(jPanel3, java.awt.BorderLayout.NORTH);

    jPanel1.setLayout(new java.awt.GridLayout(4, 4, 4, 4));

    boton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton7.setText("7");
    boton7.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton7ActionPerformed(evt);
      }
    });
    jPanel1.add(boton7);

    boton8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton8.setText("8");
    boton8.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton8ActionPerformed(evt);
      }
    });
    jPanel1.add(boton8);

    boton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton9.setText("9");
    boton9.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton9ActionPerformed(evt);
      }
    });
    jPanel1.add(boton9);

    botonDiv.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    botonDiv.setText("/");
    botonDiv.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonDivActionPerformed(evt);
      }
    });
    jPanel1.add(botonDiv);

    boton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton4.setText("4");
    boton4.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton4ActionPerformed(evt);
      }
    });
    jPanel1.add(boton4);

    boton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton5.setText("5");
    boton5.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton5ActionPerformed(evt);
      }
    });
    jPanel1.add(boton5);

    boton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton6.setText("6");
    boton6.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton6ActionPerformed(evt);
      }
    });
    jPanel1.add(boton6);

    botonMul.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    botonMul.setText("*");
    botonMul.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonMulActionPerformed(evt);
      }
    });
    jPanel1.add(botonMul);

    boton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton1.setText("1");
    boton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton1ActionPerformed(evt);
      }
    });
    jPanel1.add(boton1);

    boton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton2.setText("2");
    boton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton2ActionPerformed(evt);
      }
    });
    jPanel1.add(boton2);

    boton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton3.setText("3");
    boton3.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton3ActionPerformed(evt);
      }
    });
    jPanel1.add(boton3);

    botonRes.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    botonRes.setText("-");
    botonRes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonResActionPerformed(evt);
      }
    });
    jPanel1.add(botonRes);

    botonPunto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    botonPunto.setText(".");
    botonPunto.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonPuntoActionPerformed(evt);
      }
    });
    jPanel1.add(botonPunto);

    boton0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    boton0.setText("0");
    boton0.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        boton0ActionPerformed(evt);
      }
    });
    jPanel1.add(boton0);

    botonResultado.setBackground(new java.awt.Color(45, 115, 19));
    botonResultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    botonResultado.setForeground(new java.awt.Color(255, 255, 255));
    botonResultado.setText("=");
    botonResultado.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonResultadoActionPerformed(evt);
      }
    });
    jPanel1.add(botonResultado);

    botonSum.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
    botonSum.setText("+");
    botonSum.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonSumActionPerformed(evt);
      }
    });
    jPanel1.add(botonSum);

    botones_pan.add(jPanel1, java.awt.BorderLayout.CENTER);

    getContentPane().add(botones_pan, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
    campo.setText("0");
  }//GEN-LAST:event_clear_btnActionPerformed

  private void clearAll_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAll_btnActionPerformed
    campo.setText("0");
    superior.setText(" ");
  }//GEN-LAST:event_clearAll_btnActionPerformed

  private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
    agg('7');
  }//GEN-LAST:event_boton7ActionPerformed

  private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
    agg('8');
  }//GEN-LAST:event_boton8ActionPerformed

  private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
    agg('9');
  }//GEN-LAST:event_boton9ActionPerformed

  private void botonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDivActionPerformed
    superior.setText(campo.getText() + "/");
  }//GEN-LAST:event_botonDivActionPerformed

  private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
    agg('4');
  }//GEN-LAST:event_boton4ActionPerformed

  private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
    agg('5');
  }//GEN-LAST:event_boton5ActionPerformed

  private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
    agg('6');
  }//GEN-LAST:event_boton6ActionPerformed

  private void botonMulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMulActionPerformed
    superior.setText(campo.getText() + "*");
  }//GEN-LAST:event_botonMulActionPerformed

  private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
    agg('1');
  }//GEN-LAST:event_boton1ActionPerformed

  private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
    agg('2');
  }//GEN-LAST:event_boton2ActionPerformed

  private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
    agg('3');
  }//GEN-LAST:event_boton3ActionPerformed

  private void botonResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResActionPerformed
    if("0".equals(campo.getText())) {
      campo.setText("-");
    }else {
      superior.setText(campo.getText() + "-");
    }
  }//GEN-LAST:event_botonResActionPerformed

  private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
    if(!campo.getText().contains(".")){
      campo.setText(campo.getText() + ".");
    }
  }//GEN-LAST:event_botonPuntoActionPerformed

  private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
    agg('0');
  }//GEN-LAST:event_boton0ActionPerformed

  private void botonResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonResultadoActionPerformed
    
    double termino1, termino2, resultado;
    termino1 = " ".equals(superior.getText())? 0: Double.parseDouble(superior.getText().substring(0, superior.getText().length() - 1));
    termino2 = Double.parseDouble(campo.getText());
    char op = superior.getText().charAt(superior.getText().length() - 1);
    
    switch (op) {
      case '+': resultado = termino1 + termino2; break;
      case '-': resultado = termino1 - termino2; break;
      case '/': resultado = termino1 / termino2; break;
      case '*': resultado = termino1 * termino2; break;
      default: resultado = termino2; break;
    }
    
    superior.setText(" ");
    if ( resultado - (int)resultado == 0 && String.valueOf((int)resultado).length()<14) {
      campo.setText((int) resultado + "");
    }else if (String.valueOf(resultado).length()<14){
      campo.setText(resultado + "");
    }else{
      campo.setText("CaracterMAX");
    }
  }//GEN-LAST:event_botonResultadoActionPerformed

  private void botonSumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSumActionPerformed
    superior.setText(campo.getText() + "+");
  }//GEN-LAST:event_botonSumActionPerformed

  private void agg(char d){
    if ("0".equals(campo.getText())) {
      campo.setText(d +"");
    } else if( campo.getText().length() < 14 ) {
      campo.setText(campo.getText() + d);
    }
  }
  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    new Calculadora().setVisible(true); 
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton boton0;
  private javax.swing.JButton boton1;
  private javax.swing.JButton boton2;
  private javax.swing.JButton boton3;
  private javax.swing.JButton boton4;
  private javax.swing.JButton boton5;
  private javax.swing.JButton boton6;
  private javax.swing.JButton boton7;
  private javax.swing.JButton boton8;
  private javax.swing.JButton boton9;
  private javax.swing.JButton botonDiv;
  private javax.swing.JButton botonMul;
  private javax.swing.JButton botonPunto;
  private javax.swing.JButton botonRes;
  private javax.swing.JButton botonResultado;
  private javax.swing.JButton botonSum;
  private javax.swing.JPanel botones_pan;
  private javax.swing.JPanel cabecera_pan;
  private javax.swing.JTextField campo;
  private javax.swing.JButton clearAll_btn;
  private javax.swing.JButton clear_btn;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollBar jScrollBar1;
  private javax.swing.JLabel superior;
  private javax.swing.JLabel vacio;
  private javax.swing.JLabel vacio1;
  // End of variables declaration//GEN-END:variables
}
